### ISSUE TITLE
SCons: Failure to build with SDL 2.0.8

### ISSUE THREAD

**Issue by Muffindrake** [endless-sky/endless-sky#3709]
```
> scons
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build/release/AI.o -c -std=c++11 -Wall -O3 source/AI.cpp
In file included from /usr/include/SDL2/SDL_config.h:10:0,
                 from /usr/include/SDL2/SDL_stdinc.h:31,
                 from /usr/include/SDL2/SDL_main.h:25,
                 from /usr/include/SDL2/SDL.h:32,
                 from source/AI.cpp:35:
/usr/include/x86_64-pc-linux-gnu/SDL2/SDL_config.h:33:10: fatal error: SDL_platform.h: No such file or directory
 #include "SDL_platform.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [build/release/AI.o] Error 1
scons: building terminated because of errors.

```

I'm fairly certain this had been an issue with 2.0.{6,7}, but I didn't bother reporting at that time.

```
> sdl2-config --version                                                                   
2.0.8

> scons --version
script: v2.5.1.rel_2.5.1:3735:9dc6cee5c168[MODIFIED], 2016/11/03 14:02:02, by bdbaddog on mongodog
	engine: v2.5.1.rel_2.5.1:3735:9dc6cee5c168[MODIFIED], 2016/11/03 14:02:02, by bdbaddog on mongodog
```

My Makefile PR, given that it uses `pkg-config`, is unaffected.

**Comment by Hacklin** [comment]
I am building with `SDL 2.0.8` on `openSUSE Leap 42.3`, but I don't have this problem.

```
$ scons --version
SCons by Steven Knight et al.:
        script: v2.3.0, 2013/03/03 09:48:35, by garyo on reepicheep
        engine: v2.3.0, 2013/03/03 09:48:35, by garyo on reepicheep
        engine path: ['/usr/lib/python2.7/site-packages/SCons']
Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013 The SCons Foundation
```

**Comment by CyberShadow** [comment]
The error occurs deep inside SDL headers, so it is likely a site-specific or installation-related problem.

**Comment by endless-sky** [comment]
Just out of interest, what does `pkg-config --cflags --libs sdl2` return on your system?

**Comment by Muffindrake** [comment]
@endless-sky `--cflags --libs` is a dank and dangerous meme that needs to die. Two separate invocations with either argument.

```
> pkg-config --cflags sdl2
-D_REENTRANT -I/usr/include/SDL2
> pkg-config --libs sdl2
-lSDL2
```

**Comment by jafdy** [comment]
Yikes, calm down. If it works then what does it mater.

**Comment by filalex77** [comment]
I still have this problem on Gentoo with `scons 2.5.1`. Appending `/usr/include/SDL2` to `CPPPATH` works, so it seems to be site-specific.

**Comment by happysmash27** [comment]
Can confirm, this problem occurs on Gentoo for me too. Maybe this should be a Gentoo bug... Especially since it hasn't been fixed in over a year.

**Comment by smcv** [comment]
We've had similar issues in Debian, where some of the header locations are unusual for multiarch/multilib support (Gentoo seems to be doing something similar). It seems to be most common to encounter issues with games that include SDL headers with directives like `#include <SDL2/SDL_foo.h>`, as endless-sky does.

The intended way to use SDL headers seems to be to add appropriate `-I` flags to the compiler command line using the output of `pkg-config --cflags sdl2` or `sdl2-config --cflags` ([reference](https://wiki.libsdl.org/FAQDevelopment#Do_I_.23include_.3CSDL.h.3E_or_.3CSDL.2FSDL.h.3E.3F)), and then use `#include "SDL.h"` or `#include <SDL.h>` ([reference](https://wiki.libsdl.org/FAQLinux#How_do_I_add_SDL_to_my_project.3F)).

**Comment by TomGoodIdea** [comment]
Did anyone manage to reproduce this recently?

**Comment by TomGoodIdea** [comment]
As no one has confirmed that this is still relevant, I'll close this. Feel free to open a new issue if you encounter the problem again, but remember we're deprecating scons in favor of CMake.
