### PR TITLE
Fix compilation error on SDL before v2.0.22

### LINKED ISSUE #9608: linux-release does not build on Ubuntu 22.04
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
FAILED: source/CMakeFiles/EndlessSkyLib.dir/Release/GameWindow.cpp.o 
/usr/bin/c++ -DCMAKE_INTDIR=\"Release\" -isystem /usr/include/SDL2 -O3 -DNDEBUG -std=c++17 -flto=auto -fno-fat-lto-objects -fdiagnostics-color=always -Wall -pedantic-errors -Wold-style-cast -fno-rtti -MD -MT source/CMakeFiles/EndlessSkyLib.dir/Release/GameWindow.cpp.o -MF source/CMakeFiles/EndlessSkyLib.dir/Release/GameWindow.cpp.o.d -o source/CMakeFiles/EndlessSkyLib.dir/Release/GameWindow.cpp.o -c /home/redacted/src/sky/cmake-text-wall/source/GameWindow.cpp
/home/redacted/src/sky/cmake-text-wall/source/GameWindow.cpp: In static member function ‘static bool GameWindow::Init(bool)’:
/home/redacted/src/sky/cmake-text-wall/source/GameWindow.cpp:85:29: error: ‘SDL_HINT_VIDEODRIVER’ was not declared in this scope; did you mean ‘SDL_HINT_RENDER_DRIVER’?
   85 |                 SDL_SetHint(SDL_HINT_VIDEODRIVER, "dummy");
      |                             ^~~~~~~~~~~~~~~~~~~~
      |                             SDL_HINT_RENDER_DRIVER
```

### Steps to Reproduce

1. Get a Linux machine with Ubuntu 22.04
2. Install the packages listed in `doc/readme-cmake.md`
3. cmake --preset linux
4. cmake --build --verbose --preset linux-release

### Expected Behavior

It compiles.

### Screenshots

_No response_

### Link to save file

_No response_

### Operating System

`Linux 6.2.0-39-generic #40~22.04.1-Ubuntu x86_64 GNU/Linux`

### Game Source

GitHub Releases

### Game Version

b3a8d95ac

### Additional Information

Problem started with this hash:

4be1d8c66173fa980f3874819bd6e615576448de

which added the problematic line.

```c++
SDL_SetHint(SDL_HINT_VIDEODRIVER, "dummy");
```

### PR DESCRIPTION
**Pull request by quyykk**
## Fix Details

Fixes #9608 

## Testing Done

None, but this should work.

### CODE REVIEW

File: source/GameWindow.cpp [hunk 1]
```diff
@@ -82,7 +82,11 @@ bool GameWindow::Init(bool headless)
 
 	// When running the integration tests, don't create a window nor an OpenGL context.
 	if(headless)
+#if defined(__linux__) && !SDL_VERSION_ATLEAST(2, 0, 22)
+		setenv("SDL_VIDEODRIVER", "dummy");
```
Comment (UnorderedSigh) [inline source/GameWindow.cpp:86]: This fails to compile because it is missing the mandatory third argument to setenv: `overwrite`.

```suggestion
		setenv("SDL_VIDEODRIVER", "dummy", 0);
```

That argument tells what to do if the variable is already set. It should be 0, indicating that the variable should not be replaced if it is already set. This allows the caller to force the integration tests to run with a head.

**Review by UnorderedSigh — CHANGES_REQUESTED** [review]

File: source/GameWindow.cpp [hunk 2]
```diff
@@ -82,7 +82,11 @@ bool GameWindow::Init(bool headless)
...
+#else
 		SDL_SetHint(SDL_HINT_VIDEODRIVER, "dummy");
```
Comment (UnorderedSigh) [inline source/GameWindow.cpp:88]: To be consistent with my previous comment, you'd need to do this too:

```suggestion
		if(!getenv("SDL_VIDEODRIVER"))
			SDL_SetHint(SDL_HINT_VIDEODRIVER, "dummy");
```

I tested the `if(!getenv("SDL_VIDEODRIVER"))` in a test program, but not the `SDL_SetHint` since I don't have that version of SDL.

**Review by UnorderedSigh — CHANGES_REQUESTED** [review]

File: source/GameWindow.cpp (hunk 1 above)
Comment (quyykk) [reply source/GameWindow.cpp]: It actually should be replaced, it doesn't make sense to show the window when nothing gets drawn to the screen anyways.

File: source/GameWindow.cpp [hunk 3]
```diff
@@ -82,7 +82,11 @@ bool GameWindow::Init(bool headless)
 
 	// When running the integration tests, don't create a window nor an OpenGL context.
 	if(headless)
+#if defined(__linux__) && !SDL_VERSION_ATLEAST(2, 0, 22)
+		setenv("SDL_VIDEODRIVER", "dummy", true);
```
Comment (UnorderedSigh) [inline source/GameWindow.cpp:86]: The setenv function wants an int, not a bool.

```suggestion
		setenv("SDL_VIDEODRIVER", "dummy", 1);
```

From man 3 setenv:

```
NAME
       setenv - change or add an environment variable

SYNOPSIS
       #include <stdlib.h>

       int setenv(const char *name, const char *value, int overwrite);

       int unsetenv(const char *name);
```

**Review by UnorderedSigh — CHANGES_REQUESTED** [review]

File: source/GameWindow.cpp (hunk 3 above)
Comment (UnorderedSigh) [reply source/GameWindow.cpp:86]: There was no bool in C in the 1970s when setenv was introduced. Fortran, ever the avant-garde language, had its "logical" data type quite a while before that. However, setenv is a holdover from 1970s C + UNIX. It didn't import this advanced feature of Fortran during later C language versions.

Comment (quyykk) [reply source/GameWindow.cpp:86]: `true` converts to 1, and since the function wants a truthy/falsy value using an int is a bit weird imo

Comment (Koranir) [reply source/GameWindow.cpp:86]: Just use `SDL_TRUE` then, it was made for this exact situation.

Comment (UnorderedSigh) [reply source/GameWindow.cpp:86]: > true converts to 1, and since the function wants a truthy/falsy value using an int is a bit weird imo

UNIX programmers in the 1970s would have been appalled by that statement.

Comment (Koranir) [reply source/GameWindow.cpp:86]: > > true converts to 1, and since the function wants a truthy/falsy value using an int is a bit weird imo
> 
> UNIX programmers in the 1970s would have been appalled by that statement.

Are we UNIX programmers in the 90s?

Comment (UnorderedSigh) [reply source/GameWindow.cpp:86]: > Are we UNIX programmers in the 90s?

I don't know about you, but I live in the 2020s. The bold new era of C++20 and POSIX (UNIX) 1003.1-2017. Long live ISO/IEC 1539-1:2018!
