### ISSUE TITLE
Endless Sky tests won't compile on Ubuntu 22.04 with error about missing catch2 header (likely version 2 vs. 3 incompatibility)

### ISSUE THREAD

**Issue by UnorderedSigh** [endless-sky/endless-sky#10404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A stock Ubuntu 22.04 fails to compile the Endless Sky tests. It fails with this error:

```
FAILED: tests/CMakeFiles/EndlessSkyTests.dir/Debug/unit/src/comparators/test_byGivenOrder.cpp.o 
/usr/bin/c++ -DCMAKE_INTDIR=\"Debug\" -I/[redacted]/tests/unit/include -isystem /usr/include/SDL2 -g -std=c++20 -fdiagnostics-color=always -Wall -pedantic-errors -Wold-style-cast -fno-rtti -g -fsanitize=address,undefined,pointer-compare,pointer-subtract,unreachable,builtin,integer-divide-by-zero,vla-bound,null,return,signed-integer-overflow,bounds,alignment,bool,enum,pointer-overflow -fno-omit-frame-pointer -fsanitize=leak,vptr -MD -MT tests/CMakeFiles/EndlessSkyTests.dir/Debug/unit/src/comparators/test_byGivenOrder.cpp.o -MF tests/CMakeFiles/EndlessSkyTests.dir/Debug/unit/src/comparators/test_byGivenOrder.cpp.o.d -o tests/CMakeFiles/EndlessSkyTests.dir/Debug/unit/src/comparators/test_byGivenOrder.cpp.o -c /[redacted]/tests/unit/src/comparators/test_byGivenOrder.cpp
In file included from /[redacted]/tests/unit/src/comparators/test_byGivenOrder.cpp:16:
/[redacted]/tests/unit/include/es-test.hpp:28:10: fatal error: catch2/catch_all.hpp: No such file or directory
   28 | #include <catch2/catch_all.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

From what I've read, this is because Endless Sky is written for catch2 version 2, and hasn't migrated to version 3 yet.

- https://stackoverflow.com/questions/65098604/catch2-installation-on-ubuntu-20-04-include-catch2-catch-hpp
- https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md#top

### Steps to Reproduce

1. Install Ubuntu 22.04
2. Clone endless sky.
3. `cmake --preset linux`
4. `cmake --build --verbose --parallel 6 --preset linux-debug`
5. Witness the error.

(This also happens with gles and release.)

### Expected Behavior

Tests compile and run.

### Operating System

`Linux 6.2.0-39-generic #40~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov 16 10:53:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux`

I've got this version of catch2:

```
apt list catch2
Listing... Done
catch2/jammy,now 2.13.8-1 amd64 [installed]
catch2/jammy 2.13.8-1 i386
```

### Game Source

Built from source

### Game Version

f6fabcb1d

### Additional Information

A suitable solution would be to remove this part of docs/readme.md:

> If you're using a slower moving distro like Ubuntu or Debian (or any derivatives thereof), make sure to use at least Ubuntu 22.04 LTS or Debian 12.

Or update those version numbers to one that still works "out of the box"

**Comment by warp-core** [comment]
Install `catch2` and probably delete your `build` folder.

**Comment by UnorderedSigh** [comment]
> Install catch2 and probably delete your build folder.

I did this.

**Comment by UnorderedSigh** [comment]
I've got this version of catch2:

```
apt list catch2
Listing... Done
catch2/jammy,now 2.13.8-1 amd64 [installed]
catch2/jammy 2.13.8-1 i386
```

**Comment by warp-core** [comment]
If your distribution doesn't provide catch2 v3, build it locally or use VCPKG with `-D ES_USE_VCPKG=ON` when configuring.

**Comment by UnorderedSigh** [comment]
When I do this:

`cmake -DES_USE_VCPKG=ON --preset linux`

I get a new error:

```
CMake Warning at vcpkg/scripts/buildsystems/vcpkg.cmake:598 (_add_executable):
  Cannot generate a safe runtime search path for target EndlessSky because
  there is a cycle in the constraint graph:

    dir 0 is [/[redacted]/build/linux-gles/vcpkg_installed/x64-linux-dynamic/lib]
      dir 1 must precede it due to runtime library [libmad.so]
    dir 1 is [/[redacted]/build/linux-gles/vcpkg_installed/x64-linux-dynamic/debug/lib]
      dir 0 must precede it due to runtime library [libz.so.1]

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:231 (add_executable)


CMake Warning at vcpkg/scripts/buildsystems/vcpkg.cmake:598 (_add_executable):
  Cannot generate a safe runtime search path for target EndlessSkyTests
  because there is a cycle in the constraint graph:

    dir 0 is [/[redacted]/build/linux-gles/vcpkg_installed/x64-linux-dynamic/lib/manual-link]
    dir 1 is [/[redacted]/build/linux-gles/vcpkg_installed/x64-linux-dynamic/lib]
      dir 2 must precede it due to runtime library [libmad.so]
    dir 2 is [/[redacted]/build/linux-gles/vcpkg_installed/x64-linux-dynamic/debug/lib]
      dir 1 must precede it due to runtime library [libz.so.1]

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/CMakeLists.txt:1 (add_executable)
```

**Comment by UnorderedSigh** [comment]
It does eventually compile and run despite that error.

**Comment by UnorderedSigh** [comment]
You should update this comment in the docs/readme-cmake.md:

>  If you're using a slower moving distro like Ubuntu or Debian (or any derivatives thereof), make sure to use at least Ubuntu 22.04 LTS or Debian 12

Increase those version numbers to the oldest version of Ubuntu/Debian that still works "out of the box"

**Comment by UnorderedSigh** [comment]
There's nothing wrong with the code or build system. It's a documentation problem, and debatably so. Thus, I'm closing this issue.
