### ISSUE TITLE
TaskQueue.cpp needs to include thread in clang 23.1.0

### ISSUE THREAD

**Issue by cmyster** [endless-sky/endless-sky#12681]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

clang 23.1.0 doesn't like calling yield with no include to thread:

TaskQueue.cpp:127:16: error: no member named 'yield' in namespace 'std::this_thread'

Simple fix:

--- a/source/TaskQueue.cpp
+++ b/source/TaskQueue.cpp
@@ -17,6 +17,7 @@
 #include <algorithm>
 #include <chrono>
 #include <condition_variable>
 #include <exception>
+#include <thread>

### Steps to Reproduce

Compile with clang 23.1.0

### Expected Behavior

It compiles

### Error Log

[151/216] /usr/lib/llvm/23/bin/clang++ -DAVIF_DLL -isystem /usr/include/SDL2 -isystem /usr/include/AL  -O2 -pipe -march=native -std=c++20 -Wall -pedantic-errors -Wold-style-cast -MD -MT source/CMakeFiles/EndlessSkyLib.dir/TaskQueue.cpp.o -MF source/CMakeFiles/EndlessSkyLib.dir/TaskQueue.cpp.o.d -o source/CMakeFiles/EndlessSkyLib.dir/TaskQueue.cpp.o -c /var/tmp/portage/games-strategy/endless-sky-0.11.2/work/endless-sky-0.11.2/source/TaskQueue.cpp
FAILED: [code=1] source/CMakeFiles/EndlessSkyLib.dir/TaskQueue.cpp.o 
/usr/lib/llvm/23/bin/clang++ -DAVIF_DLL -isystem /usr/include/SDL2 -isystem /usr/include/AL  -O2 -pipe -march=native -std=c++20 -Wall -pedantic-errors -Wold-style-cast -MD -MT source/CMakeFiles/EndlessSkyLib.dir/TaskQueue.cpp.o -MF source/CMakeFiles/EndlessSkyLib.dir/TaskQueue.cpp.o.d -o source/CMakeFiles/EndlessSkyLib.dir/TaskQueue.cpp.o -c /var/tmp/portage/games-strategy/endless-sky-0.11.2/work/endless-sky-0.11.2/source/TaskQueue.cpp
/var/tmp/portage/games-strategy/endless-sky-0.11.2/work/endless-sky-0.11.2/source/TaskQueue.cpp:127:16: error: no member named 'yield' in namespace 'std::this_thread'
  127 |                 this_thread::yield();
      |                              ^~~~~

### Operating System

Linux central-pc 7.2.4-gentoo-dist-bin #1 SMP PREEMPT_DYNAMIC

### Game Source

GitHub Releases

### Game Version

0.11.2

**Comment by cmyster** [comment]
sorry, bad paste:

--- a/source/TaskQueue.cpp
+++ b/source/TaskQueue.cpp
@@ -17,6 +17,7 @@
 #include \<algorithm\>
 #include \<chrono\>
 #include \<condition_variable\>
 #include \<exception\>
+#include \<thread\>

**Comment by TomGoodIdea** [comment]
Feel free to open a PR with the fix.
